kind: Service
apiVersion: v1
metadata:
  name: jobvacancy
  labels:
    app: jobvacancy
spec:
  selector:
    app: jobvacancy
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
  type: NodePort